# Generated by Django 4.2.5 on 2023-10-03 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_alter_todo_dadeline_alter_todo_finished_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="dadeline",
            new_name="deadline",
        ),
    ]
